### ISSUE TITLE
Verify filters - [Brightness,Bulge Distortion,CGA Colorspace,Color Invert,Color Matrix,Contrast,Crosshatch,Exposure,False Color,Gamma,Grayscale,Halftone,Highlight Shadow,Hue] 

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_image_filters#10]

**Comment by nataliiazabiiaka** [comment]
🆗 Brightness
🆗 Bulge Distortion
🆗 CGA Colorspace
🆗 Color Invert
❌ Color Matrix ( don't understand what is it)
🆗 Contrast
🆗 Crosshatch
🆗 Exposure (but too abrupt transitions)
🆗 False Color
🆗 Gamma
🆗 Grayscale
🆗 Halftone
🆗 Highlight Shadow(but don't see difference between highlight's slider or shadow's slider)
🆗 Hue
+ wherever you can enter numbers, you can put Russian letters
