### ISSUE TITLE
Verify filters - [Luminance,Luminance Threshold,Monochrome,Opacity,Pixelation,Posterize,RGB,Saturation,Solarize,Swirl,Vibrance,Vignette,White Balance,Zoom Blur] 

### ISSUE THREAD

**Issue by nikolaydymura** [nikolaydymura/flutter_image_filters#11]

**Comment by nataliiazabiiaka** [comment]
❌ Luminance (same like Grayscale)
🆗 Luminance Threshold
🆗 Monochrome (you can write some letters near numbers)
🆗 Opacity
🆗 Pixelation
❌ Posterize (you can see slider's changes only on the start)
❌ RGB (messed up colors)
🆗 Saturation
🆗 Solarize (you can write some Russian letters near numbers)
🆗 Swirl (you can write some Russian letters near numbers)
🆗 Vibrance (you can write some Russian letters near numbers)
🆗 Vignette (you can write some letters near numbers)
❌ White Balance (+you can write some Russian letters near numbers)
🆗 Zoom Blur (you can write some Russian letters near numbers)
