### ISSUE TITLE
image importing by value chnages everytime

### ISSUE THREAD

**Issue by yashanghan22** [nikolaydymura/flutter_image_filters#12]
![image import every time](https://user-images.githubusercontent.com/53462202/211315193-9af07bc5-7923-48b3-b0e8-dfc64774ca03.jpg)

when i chnage value of any brightness,contrast,exposure,etc. it's importing image every time as i attached a **ScreenShot** of Debug Console so that effects can not apply smoothly.
when i give only one configuration to my image it will work fine. 
**GroupShaderConfig** taking some time and re buid widget end then it's showing output. and it's **blinking** while changing values.

so what's the solution of this?

**Comment by bh-jayadeep** [comment]
Experiencing the same issue.

**Comment by nikolaydymura** [comment]
In the future version will be solution for some of the filters. 
@yashanghan22 @bh-jayadeep, can you list what filters you are using so I can say if this future fix will help you?

**Comment by yashanghan22** [comment]
right now i am using brightness,contrast,exposure,saturation,hue but i wanna tell you that it only happens when **groupshader** is in used if you use only one filter using groupshader it will be same. so main problem is **groupshader**.

**Comment by bh-jayadeep** [comment]
GroupShaderConfiguration editConfig = GroupShaderConfiguration();
    editConfig.add(BrightnessShaderConfiguration()..brightness = brightness);
    editConfig.add(ContrastShaderConfiguration()..contrast = contrast);
    editConfig.add(SaturationShaderConfiguration()..saturation = saturation);
    editConfig.add(GammaShaderConfiguration()..gamma = gamma);
    editConfig
        .add(WhiteBalanceShaderConfiguration()..temperature = whiteBalance);

    updateConfiguration(editConfig);

**Comment by nikolaydymura** [comment]
@yashanghan22 @bh-jayadeep In version 0.0.6 was added new `BunchShaderConfiguration` class. You can find how to use it in [GENERATE.md](https://github.com/nikolaydymura/flutter_image_filters/blob/main/GENERATE.md).
