### ISSUE TITLE
Dependency issue with latest flutter

### ISSUE THREAD

**Issue by bh-jayadeep** [nikolaydymura/flutter_image_filters#18]
I've upgraded flutter and it is causing dependency issues.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/117913135/215265929-57312577-9ff1-4972-874a-a987c5f599c5.png">

**Comment by nikolaydymura** [comment]
Try to do
`flutter clean
flutter pub get`

**Comment by nikolaydymura** [comment]
Flutter 3.7.1 must be the lowest one to use
