### ISSUE TITLE
Transparent Image Filters

### ISSUE THREAD

**Issue by bh-jayadeep** [nikolaydymura/flutter_image_filters#20]
The filters get applied on transparent Pixels as well and create a white box in the preview.

Before
![Screenshot 2023-03-07 at 6 59 36 PM](https://user-images.githubusercontent.com/117913135/223436641-833355a1-204e-46c9-8eea-282ad3d6f81e.png)

After

![Screenshot 2023-03-07 at 6 59 43 PM](https://user-images.githubusercontent.com/117913135/223436622-9b5cd7e7-6f20-4ad0-96c8-2748cb38eb1c.png)

**Comment by nikolaydymura** [comment]
@bh-jayadeep Thanks for the report, what filters except `Brightness`  has the same behavior?

**Comment by nikolaydymura** [comment]
Fixed in `0.0.12`
