### ISSUE TITLE
low quality for LUT, HALD applied result 

### ISSUE THREAD

**Issue by hankyungs** [nikolaydymura/flutter_image_filters#27]
The quality of the results with the application of LUT or Hald is low.

![IMG_1227](https://github.com/nikolaydymura/flutter_image_filters/assets/41785064/34b8729e-d7a4-4d7f-86fd-bd5f68f047f8)

(ignore white grid line)

**Comment by hankyungs** [comment]
Loosing quality only in ios. Android is fine

**Comment by nikolaydymura** [comment]
@hankyungs Please try to disable [impeller](https://docs.flutter.dev/perf/impeller) on iOS. We noticed it is still not stable to be used with shaders.

To disable Impeller on iOS when deploying your app, add the following tags under the top-level <dict> tag in your app’s Info.plist file.

content_copy
  <key>FLTEnableImpeller</key>
  <false />

**Comment by hankyungs** [comment]
Resolved issue. Thanks
