### ISSUE TITLE
Multiple Configurations on a single image.

### ISSUE THREAD

**Issue by sjayadeep** [nikolaydymura/flutter_image_filters#8]
`final texture = await TextureSource.fromAsset('demo.jpeg');
final configuration = BrightnessShaderConfiguration();
configuration.brightness = 0.5;
final image = await configuration.export(texture, texture.size);`

How to update saturation or any other configuration on top of this?

**Comment by nikolaydymura** [comment]
In version 0.0.4 was added `TextureSource.fromImage`, it allows easily converting of the processed image back to `TextureSource`.

@sjayadeep You can find an example of usage [TextureSource.fromImage](https://github.com/nikolaydymura/flutter_image_filters#pipeline-export)

**Comment by sjayadeep** [comment]
Thanks. It would be great if it works with the ImageShaderPreview as well.

`ImageShaderPreview(
                            texture: imageEditController.image,
                            configurations:[
brightnessConfiguration,
contrastConfiguration,
....
]),`

Something like this.

**Comment by yashanghan22** [comment]
i am not able to impliment **GroupSaderConfiguration** beacuse it has not **PipelineImageShaderPreview**  Using this package which example are shown in this git repo.

**Comment by nikolaydymura** [comment]
Try the 0.0.5 version. You can find `PipelineImageShaderPreview` and `GroupShaderConfiguration`
