### ISSUE TITLE
i am not able to impliment **GroupSaderConfiguration**.

### ISSUE THREAD

**Issue by yashanghan22** [nikolaydymura/flutter_image_filters#9]
i am not able to impliment **GroupSaderConfiguration** beacuse it has not **PipelineImageShaderPreview**  Using this package which example are shown in this git repo.

_Originally posted by @yashanghan22 in https://github.com/nikolaydymura/flutter_image_filters/issues/8#issuecomment-1375076874_

**Comment by nikolaydymura** [comment]
@yashanghan22 Try version 0.0.5

**Comment by bh-jayadeep** [comment]
flutter_image_filters: ^0.0.5

does not have GroupShaderConfiguration or PipelineImageShaderPreview
